name: eco_prime_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Quản lý trạng thái
  flutter_bloc: ^8.1.3

  # Gọi API
  dio: ^5.4.0

  # Lưu trữ bảo mật
  flutter_secure_storage: ^9.0.0

  # Quản lý biến môi trường
  flutter_dotenv: ^5.1.0

  # Giải mã JWT
  jwt_decoder: ^2.0.1

  # Cấu hình lưu trữ cục bộ (Bổ sung cái này)
  shared_preferences: ^2.3.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env

  uses-material-design: true